project:
  type: website

website:
  title: "FISHFAN"
  search: true
  navbar:
    background: primary
    logo: wpgLogo.png
    toggle-position: right
    right:
      - href: Travel.qmd
        text: Travel
      - href: index.qmd
        text: Home
      - about.qmd
      - icon: tools
        text: options
        menu:
          - text: optionA
            href: optionA.qmd
          - text: optionB
            href: optionB.qmd
          - text: optionC
            href: optionC.qmd
  announcement:
    icon: info-circle
    dismissable: true
    content: "**Mayday - this is some information that you should pay attention to"
    type: primary
    position: below-navbar
  page-footer: "copyright 2021, FishFanWpg"
     

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

